org: fleite
app: hello-sls
service: hello-sls
  configValidationMode: error

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      -http:
        method: GET
        path: hello

